# Generated by Django 4.0.6 on 2022-07-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='price_komga',
        ),
        migrations.AddField(
            model_name='phone',
            name='price_konga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price_jumia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
