# Generated by Django 4.0.6 on 2022-08-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare_app', '0002_alter_review_phone'),
        ('price_compare_app', '0002_remove_phone_slug'),
    ]

    operations = [
    ]
