# Generated by Django 4.0.6 on 2022-07-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare_app', '0003_phone_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='review_stars',
            new_name='star_reviews',
        ),
    ]
