# Generated by Django 4.0.6 on 2022-08-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare_app', '0003_remove_wishlist_phone_wishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_compare_app.phone'),
        ),
        migrations.DeleteModel(
            name='wishitem',
        ),
    ]
