# Generated by Django 4.0.6 on 2022-08-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare_app', '0004_rename_review_stars_phone_star_reviews'),
        ('price_compare_app', '0005_remove_wishlist_phone_wishitem'),
    ]

    operations = [
    ]
