# Generated by Django 4.0.6 on 2022-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_compare_app', '0006_merge_20220802_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
